### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by Clararigaud** [osunyorg/bordeaux-iut-de-bordeaux#5]
- [x] Logo en footer
- [x] Résumé sur les pages formations 
- [x] Contacts dans les formations  -> créer des roles + ajouter une section en override "6 - Contacts"
- [x] Macaron licence validée
- [x] Refaire une passe sur les tailles d'images
- [x] Passer les titres et summary sur 8 cols et pas 9
- [x] Remonter dans les diagonales
- [x] couleur table des matieres moches 
- [x] taille de typo dans formations plus poids
